"""统一错误码枚举"""
from enum import Enum


class ErrorCode(str, Enum):
    """应用错误码"""

    # 通用
    SUCCESS = "SUCCESS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"

    # 认证 (1xxx)
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    LOGIN_FAILED = "LOGIN_FAILED"
    USER_EXISTS = "USER_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_EXISTS = "EMAIL_EXISTS"

    # 文件 (2xxx)
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FOLDER_NOT_FOUND = "FOLDER_NOT_FOUND"
    NAME_CONFLICT = "NAME_CONFLICT"
    CIRCULAR_MOVE = "CIRCULAR_MOVE"

    # 上传 (3xxx)
    UPLOAD_FAILED = "UPLOAD_FAILED"
    UPLOAD_INIT_FAILED = "UPLOAD_INIT_FAILED"
    UPLOAD_SESSION_NOT_FOUND = "UPLOAD_SESSION_NOT_FOUND"
    UPLOAD_SESSION_EXPIRED = "UPLOAD_SESSION_EXPIRED"
    CHUNK_OUT_OF_RANGE = "CHUNK_OUT_OF_RANGE"
    CHUNK_UPLOAD_FAILED = "CHUNK_UPLOAD_FAILED"

    # 存储 (4xxx)
    STORAGE_EXCEEDED = "STORAGE_EXCEEDED"
    QUOTA_TOO_SMALL = "QUOTA_TOO_SMALL"

    # 下载 (5xxx)
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
